package com.sec.filing.analysis.parse.jflex;

public enum JflexTokenType {
	 TOC_STRING, INDEX_STRING, MDA_STRING, FSSD_STRING, 
	 
	 TOC, TOC_ITEM_STRING, TOC_MDA_STRING, TOC_FSSD_STRING, TOC_MDA_STRING_WITH_NUMBER, TOC_FSSD_STRING_WITH_NUMBER, 
	 MDA_STRING_FIRST_HALF,
	 
	 BINARY_FILE,
	 
	 PAGE_BREAK, HYPHEN_PAGE_BREAK,
	 EOF
}
